spring.application.name=chatbot

# ==========================================
# MySQL Database
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/ai_chatbot?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Namratha@2006

# ==========================================
# JPA / Hibernate
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true